/*
* generated by Xtext
*/
package php.ware.ui.contentassist;

import php.ware.ui.contentassist.AbstractConfigProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ConfigProposalProvider extends AbstractConfigProposalProvider {

}
